---
- name: install nginx
  hosts: all
  become: true
  
  tasks:
  - name: install nginx
    yum:
      name: nginx
      state: install
  - name: start nginx  
    service:
      name: nginx
      state: started
    
